apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-backend
  template:
    metadata:
      labels:
        app: py-backend
    spec:
      containers:
      - name: py-backend
        image: zvdy/py-backend:tag # Replace with your image if you want to use your own
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi